import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { auth } from "~/server/auth";
import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "./_components/nav/navbar";
import Footer from "./_components/nav/footer";

export const metadata: Metadata = {
  title: "SWE Training | RoBorregos",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-primary">
        <Navbar session={session} />
        <div className="">
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </div>
        <Footer />
      </body>
    </html>
  );
}
